Aliyaba/ManagementClient/Controllers/ImageController.cs
using BussinesLogic.Helpers;
using Common.DTOs;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Client.Controllers
{
    public class ImageController : Controller
    {
        public ActionResult Index()
        {


            return View("AddImage");
        }

        public ActionResult AddImage(HttpPostedFileBase upload, string ProductCode)
        {
            if (upload != null && ProductCode != null)
            {
                byte[] imageData = null;
                using (var image = new BinaryReader(upload.InputStream))
                {
                    imageData = image.ReadBytes(upload.ContentLength);
                }

                H_Photo HP = H_Photo.getInstance();

                DTO_Photo _P = new DTO_Photo();
                _P.Photo = imageData;
                _P.ProductCode = ProductCode;

                HP.AddPhoto(_P);
            }

            return RedirectToAction("Index");
        }
    }
}

Aliyaba/ManagementClient/Controllers/OrdersPrepareController.cs
using BussinesLogic.Helpers;
using Common.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Client.Controllers
{
    public class OrdersPrepareController : Controller
    {
        public ActionResult Index()
        {
            H_Order HO = H_Order.getInstance();
            H_OrdersDetail HOD = H_OrdersDetail.getInstance();

            List<DTO_Order> O = HO.GetPendingOrders();
            List<DTO_OrdersDetail> OD = new List<DTO_OrdersDetail>();

            foreach (DTO_Order Or in O)
            {
                foreach (DTO_OrdersDetail _OrD in HOD.GetOrdersDetailByOrderID(Or.ID))
                {
                    OD.Add(_OrD);
                }
            }

            ViewBag.OrdersCount = O.Count;
            ViewBag.Orders = O.OrderByDescending(o => o.IsExpress);
            ViewBag.OrdersDetails = OD;

            return View("SelectOrder");
        }
        public string GetProductNameToShowOrders(string _Code)
        {
            DTO_Product _P = new DTO_Product();

            H_Product HP = H_Product.getInstance();

            _P = HP.GetProductByCode(_Code);

            return _P.Name;
        }

        public ActionResult GetOrderToPrepare(int _ID)
        {
            H_OrdersDetail HOD = H_OrdersDetail.getInstance();
            H_State HS = H_State.getInstance();

            List<DTO_OrdersDetail> OD = new List<DTO_OrdersDetail>();
            List<DTO_OrderPrepareDetail> OPD = new List<DTO_OrderPrepareDetail>();

            DTO_State _S = new DTO_State();
            _S.Date = DateTime.Now;
            _S.EmployeeID = int.Parse(Session["UserID"].ToString());
            _S.State = States.Preparing;
            _S.Name = "En Preparación";
            _S.OrderID = _ID;
            HS.AddState(_S);

            foreach (DTO_OrderPrepareDetail _OPD in HOD.GetOrdersPrepareDetailByOrderID(_ID))
            {
                OPD.Add(_OPD);
            }

            OD = HOD.GetOrdersDetailByOrderID(_ID);

            ViewBag.OrdersDetail = OD;
            ViewBag.OrdersPrepareDetail = OPD.OrderBy(o => o.Location);

            return View("Prepare");
        }
        public ActionResult FinishPrepare(int _OrderID)
        {
            H_State HS = H_State.getInstance();
            H_ReservedStock HRS = H_ReservedStock.getInstance();

            DTO_State _S = new DTO_State();
            _S.EmployeeID = int.Parse(Session["UserID"].ToString());
            _S.Date = DateTime.Now;
            _S.Name = "Preparado";
            _S.State = States.Prepared;
            _S.OrderID = _OrderID;

            HS.AddState(_S);

            HRS.FinishPrepare(_OrderID);

            return RedirectToAction("Index");
        }
    }
}

Aliyaba/ManagementClient/Views/Shared/_CRUD.cshtml
@{
    string AddFormTitle = ViewBag.AddFormTitle;
    string CurrentController = ViewBag.CurrentController;
}

<div class="row mt-5">
    <div class="col-12">
        <div class="card shadow">
            <div class="card-body">
                @Html.Action("GetTableBody", CurrentController)
            </div>
        </div>
    </div>

    <div class="modal fade" id="AddModal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">@AddFormTitle</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @Html.Action("GetAddForm", CurrentController)
                </div>
            </div>
        </div>
    </div>
</div>

Aliyaba/ManagementClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Vendor/Css")
    @Styles.Render("~/Content/SideBar.css")
</head>
<body>
    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="bg-dark border-right border-dark shadow" id="sidebar-wrapper">
            <div class="sidebar-heading text-center"><h4>@Session["UserName"].ToString().ToUpper()</h4></div>
            <p class="text-muted text-center" style="margin-top: -1rem">@Session["UserPosition"].ToString().ToUpper()</p>
            @{
                if (Session["UserPosition"].ToString() == "administrador")
                {
                    <ul class="list-group mt-3 border-top border-secondary list-group-flush">
                        <li><a href="@Url.Action("Index", "Order")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-boxes mr-1" style="width: 30px; font-size: 1.5rem"></i> Pedidos</a></li>
                        <li><a href="@Url.Action("Index", "Delivery")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-truck mr-1" style="width: 30px; font-size: 1.5rem"></i> Repartos</a></li>
                        <li><a href="@Url.Action("Home", "Customer")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-users mr-1" style="width: 30px; font-size: 1.5rem"></i> Clientes</a></li>
                        <li><a href="@Url.Action("Home", "Location")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-map-marker-alt ml-1" style="width: 30px; font-size: 1.5rem"></i> Ubicaciones</a></li>
                        <li><a href="@Url.Action("Index", "Employee")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-people-carry mr-1" style="width: 30px; font-size: 1.5rem"></i> Empleados</a></li>
                        <li><a href="@Url.Action("Home", "Product")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-box mr-1" style="width: 30px; font-size: 1.5rem"></i> Productos</a></li>
                        <li><a href="@Url.Action("Home", "Category")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-filter   mr-1" style="width: 30px; font-size: 1.5rem"></i> Categorías</a></li>
                        <li><a href="@Url.Action("Index", "Image")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-images mr-1" style="width: 30px; font-size: 1.5rem"></i> Imágenes</a></li>
                        <li><a href="@Url.Action("Index", "Stock")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-clipboard-list ml-1" style="width: 30px; font-size: 1.5rem"></i> Stocks</a></li>
                        <li><a href="@Url.Action("Home", "Price")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-tags mr-1" style="width: 30px; font-size: 1.5rem"></i> Precios</a></li>
                        <li><a href="@Url.Action("Index", "Reports")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-chart-bar mr-1" style="width: 30px; font-size: 1.5rem"></i> Reportes</a></li>
                        <li><a href="@Url.Action("LogOut", "Dashboard")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-sign-out-alt mr-1" style="width: 30px; font-size: 1.5rem"></i> Cerrar Sesión</a></li>
                    </ul>
                }
                else if (Session["UserPosition"].ToString() == "gerente")
                {
                    <ul class="list-group mt-3 border-top border-secondary list-group-flush">
                        <li><a href="@Url.Action("Index", "Order")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-boxes mr-1" style="width: 30px; font-size: 1.5rem"></i> Pedidos</a></li>
                        <li><a href="@Url.Action("Index", "OrdersPrepare")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-box-open mr-1" style="width: 30px; font-size: 1.5rem"></i> Preparar Pedido</a></li>
                        <li><a href="@Url.Action("Index", "Delivery")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-truck mr-1" style="width: 30px; font-size: 1.5rem"></i> Repartos</a></li>
                        <li><a href="@Url.Action("Prepare", "Delivery")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-truck-loading mr-1" style="width: 30px; font-size: 1.5rem"></i> Preparar Reparto</a></li>
                        <li><a href="@Url.Action("SelectDelivery", "Delivery")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-truck-moving mr-1" style="width: 30px; font-size: 1.5rem"></i> Iniciar Reparto</a></li>
                        <li><a href="@Url.Action("Home", "Customer")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-users mr-1" style="width: 30px; font-size: 1.5rem"></i> Clientes</a></li>
                        <li><a href="@Url.Action("Home", "Location")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-map-marker-alt ml-1" style="width: 30px; font-size: 1.5rem"></i> Ubicaciones</a></li>
                        <li><a href="@Url.Action("Home", "Product")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-box mr-1" style="width: 30px; font-size: 1.5rem"></i> Productos</a></li>
                        <li><a href="@Url.Action("Home", "Category")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-filter   mr-1" style="width: 30px; font-size: 1.5rem"></i> Categorías</a></li>
                        <li><a href="@Url.Action("Index", "Image")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-images mr-1" style="width: 30px; font-size: 1.5rem"></i> Imágenes</a></li>
                        <li><a href="@Url.Action("Index", "Stock")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-clipboard-list ml-1" style="width: 30px; font-size: 1.5rem"></i> Stocks</a></li>
                        <li><a href="@Url.Action("Home", "Price")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-tags mr-1" style="width: 30px; font-size: 1.5rem"></i> Precios</a></li>
                        <li><a href="@Url.Action("Index", "Reports")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-chart-bar mr-1" style="width: 30px; font-size: 1.5rem"></i> Reportes</a></li>
                        <li><a href="@Url.Action("LogOut", "Dashboard")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-sign-out-alt mr-1" style="width: 30px; font-size: 1.5rem"></i> Cerrar Sesión</a></li>
                    </ul>
                }
                else if (Session["UserPosition"].ToString() == "empaquetador")
                {
                    <ul class="list-group mt-3 border-top border-secondary list-group-flush">
                        <li><a href="@Url.Action("Index", "OrdersPrepare")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-box-open mr-1" style="width: 30px; font-size: 1.5rem"></i> Preparar Pedido</a></li>
                        <li><a href="@Url.Action("LogOut", "Dashboard")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-sign-out-alt mr-1" style="width: 30px; font-size: 1.5rem"></i> Cerrar Sesión</a></li>
                    </ul>
                }
                else if (Session["UserPosition"].ToString() == "reponedor")
                {
                    <ul class="list-group mt-3 border-top border-secondary list-group-flush">
                        <li><a href="@Url.Action("Home", "Stocks")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-clipboard-list ml-1" style="width: 30px; font-size: 1.5rem"></i> Stocks</a></li>
                        <li><a href="@Url.Action("LogOut", "Dashboard")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-sign-out-alt mr-1" style="width: 30px; font-size: 1.5rem"></i> Cerrar Sesión</a></li>
                    </ul>
                }
                else if (Session["UserPosition"].ToString() == "repartidor")
                {
                    <ul class="list-group mt-3 border-top border-secondary list-group-flush">
                        <li><a href="@Url.Action("SelectDelivery", "Delivery")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-truck-moving mr-1" style="width: 30px; font-size: 1.5rem"></i>Seleccionar Reparto</a></li>
                        <li><a href="@Url.Action("LogOut", "Dashboard")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-sign-out-alt mr-1" style="width: 30px; font-size: 1.5rem"></i> Cerrar Sesión</a></li>
                    </ul>
                }
                else if (Session["UserPosition"].ToString() == "preparador")
                {
                    <ul class="list-group mt-3 border-top border-secondary list-group-flush">
                        <li><a href="@Url.Action("Prepare", "Delivery")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-truck mr-1" style="width: 30px; font-size: 1.5rem"></i> Repartos</a></li>
                        <li><a href="@Url.Action("LogOut", "Dashboard")" class="list-group-item list-group-item-action bg-dark" style="border: none"><i class="fas fa-sign-out-alt mr-1" style="width: 30px; font-size: 1.5rem"></i> Cerrar Sesión</a></li>
                    </ul>
                }
            }
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">

            <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow border-bottom border-dark">
                <button class="btn" id="menu-toggle"><span class="navbar-toggler-icon"></span></button>
            </nav>

            <div class="container-fluid p-md-5">
                @RenderBody()
            </div>
        </div>
        <!-- /#page-content-wrapper -->
    </div>
    <!-- /#wrapper -->

    @Scripts.Render("~/Vendor/Js")
    <script src="https://kit.fontawesome.com/e39886f78e.js" crossorigin="anonymous"></script>
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>
</body>
</html>