Aliyaba/ManagementClient/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.UI.WebControls;
using BussinesLogic.Helpers;
using Common.DTOs;

namespace Client.Controllers
{
    public class LocationController : Controller
    {
        public ActionResult Home()
        {
            List<string> TableHeaders = new List<string>();
            TableHeaders.Add("Latitud");
            TableHeaders.Add("Longitud");
            TableHeaders.Add("Nombre de Usuario");
            ViewBag.CurrentController = "Location";
            ViewBag.TableHeaders = TableHeaders;
            ViewBag.AddFormTitle = "Agregar una locación";
            return View("_CRUD");
        }
        public ActionResult GetAddForm()
        {
            return PartialView("_AddForm");
        }
        public ActionResult GetTableBody()
        {
            H_Location HL = H_Location.getInstance();

            List<DTO_Location> Locations = HL.GetLocations();

            ViewBag.TableList = Locations;

            return PartialView("_TableBody");
        }


        public ActionResult AddLocation(DTO_Location _L)
        {
            H_Location HL = H_Location.getInstance();

            HL.AddLocation(_L);

            return RedirectToAction("Home");
        }
        public ActionResult Delete(int ID)
        {
            H_Location HL = H_Location.getInstance();

            HL.DeleteLocation(ID);

            return RedirectToAction("Home");
        }
    }
}

Aliyaba/ManagementClient/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Client.Controllers
{
    public class MapController : Controller
    {
        // GET: Map
        public ActionResult GetMap()
        {
            return PartialView("_Map");
        }
    }
}

Aliyaba/ManagementClient/Views/Location/_AddForm.cshtml
@*@{ Layout = null;}
@model Common.DTOs.DTO_Location

@using (Html.BeginForm("AddLocation", "Location"))
{
    @Html.LabelFor(model => model.Latitude, "Latitud")
    @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = " input form-control bg-secondary text-light shadow", @id = "latitude" } })
    @Html.LabelFor(model => model.Longitude, "Longitud")
    @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "input form-control bg-secondary text-light shadow", @id = "longitude" } })
    @Html.Action("GetMap", "Map")
    @Html.LabelFor(model => model.CustomerUsername, "Usuario del Cliente")
    @Html.EditorFor(model => model.CustomerUsername, new { htmlAttributes = new { @class = "input form-control bg-secondary text-light shadow" } })
    <button class="btn btn-primary mt-3" type="submit" id="btn_Validar" disabled>Agregar</button>
    <br />
    <i id="labelError" class="text-danger hidden">
        Debe completar todos los campos antes de Agregar
    </i>
}

@Scripts.Render("~/Vendor/Js")

<script>
    $('.input').keyup(function () {
        var count = $('.input').length;
        var aux = 0;
        $('.input').each(function () {
            if ($(this).val().length > 0) {
                aux += 1
            }
        })

        if (count != aux) {
            $('#btn_Validar').attr('disabled', true);
        }
        else {
            $('#btn_Validar').removeAttr("disabled");
        }
    });
</script>*@

Aliyaba/ManagementClient/Views/Location/_TableBody.cshtml
@{ Layout = null;}
@model Common.DTOs.DTO_Location
@{
    foreach (Common.DTOs.DTO_Location L in ViewBag.TableList)
    {
        <div class="dataDiv" style="display: none" data-username="@L.CustomerUsername" data-description="@L.Description"></div>
    }
    <table id="table" data-classes="table table-hover table-borderless"></table>

    @Scripts.Render("~/Vendor/Js")

    <script>
        var dat = [];
        $('.dataDiv').each(function () {
            var dd = {}
            dd.Description = $(this).data("description");
            dd.CustomerUsername = $(this).data("username");
            dat.push(dd)
        })
        $('#table').bootstrapTable({
            pagination: true,
            search: true,
            columns: [{
                field: 'CustomerUsername',
                title: 'Nombre de Usuario'
            }, {
                field: 'Description',
                title: 'Descripción'
            },],
            data: dat
        })
    </script>
}
@*@Url.Action("Delete", "Customer", new { Document = C.Document, DocumentTypeName = C.DocumentTypeName })
    @Url.Action("Home", "Customer", new { ID = @C.UserName })*@